export const MICROSERVICE_TOKENS = {
  USER_SERVICE: 'USER_SERVICE',
  COURSE_SERVICE: 'COURSE_SERVICE',
  ENROLLMENT_SERVICE: 'ENROLLMENT_SERVICE',
  PAYMENT_SERVICE: 'PAYMENT_SERVICE',
  AUTH_SERVICE: 'AUTH_SERVICE',
  CONTENT_SERVICE: 'CONTENT_SERVICE',
  NOTIFICATION_SERVICE: 'NOTIFICATION_SERVICE',
  MEDIA_SERVICE: 'MEDIA_SERVICE',
  PROGRESS_SERVICE: 'PROGRESS_SERVICE',
};

export const MICROSERVICE_QUEUES = {
  USER_QUEUE: 'user_queue',
  COURSE_QUEUE: 'course_queue',
  ENROLLMENT_QUEUE: 'enrollment_queue',
  PAYMENT_QUEUE: 'payment_queue',
  AUTH_QUEUE: 'auth_queue',
  CONTENT_QUEUE: 'content_queue',
  NOTIFICATION_QUEUE: 'notification_queue',
  MEDIA_QUEUE: 'media_queue',
  PROGRESS_QUEUE: 'progress_queue',
};

export const EVENTS = {
  USER_CREATED: 'user.created',
  USER_UPDATED: 'user.updated',
  USER_DELETED: 'user.deleted',
  COURSE_CREATED: 'course.created',
  COURSE_UPDATED: 'course.updated',
  COURSE_DELETED: 'course.deleted',
  ENROLLMENT_CREATED: 'enrollment.created',
  ENROLLMENT_UPDATED: 'enrollment.updated',
  ENROLLMENT_DELETED: 'enrollment.deleted',
  PAYMENT_CREATED: 'payment.created',
  PAYMENT_UPDATED: 'payment.updated',
  PAYMENT_DELETED: 'payment.deleted',
  CONTENT_CREATED: 'content.created',
  CONTENT_UPDATED: 'content.updated',
  CONTENT_DELETED: 'content.deleted',
  NOTIFICATION_CREATED: 'notification.created',
  NOTIFICATION_UPDATED: 'notification.updated',
  NOTIFICATION_DELETED: 'notification.deleted',
  MEDIA_CREATED: 'media.created',
  MEDIA_UPDATED: 'media.updated',
  MEDIA_DELETED: 'media.deleted',
  PROGRESS_CREATED: 'progress.created',
  PROGRESS_UPDATED: 'progress.updated',
  PROGRESS_DELETED: 'progress.deleted',
};

export const PATTERNS = {
  AUTH: {
    VALIDATE_TOKEN: 'auth.validateToken',
    GET_USER_FROM_TOKEN: 'auth.getUserFromToken',
    LOGIN: 'auth.login',
    REGISTER: 'auth.register',
    REFRESH_TOKEN: 'auth.refreshToken',
    LOGOUT: 'auth.logout',
    REQUEST_PASSWORD_RESET: 'auth.requestPasswordReset',
    RESET_PASSWORD: 'auth.resetPassword',
  },
  USER: {
    FIND_ALL: 'user.findAll',
    FIND_ONE: 'user.findOne',
    CREATE: 'user.create',
    UPDATE: 'user.update',
    DELETE: 'user.delete',
  },
  COURSE: {
    FIND_ALL: 'course.findAll',
    FIND_ONE: 'course.findOne',
    CREATE: 'course.create',
    UPDATE: 'course.update',
    DELETE: 'course.delete',
  },
  ENROLLMENT: {
    FIND_ALL: 'enrollment.findAll',
    FIND_ONE: 'enrollment.findOne',
    CREATE: 'enrollment.create',
    UPDATE: 'enrollment.update',
    DELETE: 'enrollment.delete',
  },
  PAYMENT: {
    FIND_ALL: 'payment.findAll',
    FIND_ONE: 'payment.findOne',
    CREATE: 'payment.create',
    UPDATE: 'payment.update',
    DELETE: 'payment.delete',
    PROCESS: 'payment.process',
  },
  CONTENT: {
    FIND_ALL: 'content.findAll',
    FIND_BY_COURSE: 'content.findByCourse',
    FIND_BY_MODULE: 'content.findByModule',
    FIND_ONE: 'content.findOne',
    CREATE: 'content.create',
    UPDATE: 'content.update',
    DELETE: 'content.delete',
    CHANGE_STATUS: 'content.changeStatus',
  },
  NOTIFICATION: {
    FIND_ALL: 'notification.findAll',
    FIND_BY_USER: 'notification.findByUser',
    FIND_ONE: 'notification.findOne',
    CREATE: 'notification.create',
    UPDATE: 'notification.update',
    REMOVE: 'notification.remove',
    MARK_AS_READ: 'notification.markAsRead',
    MARK_ALL_AS_READ: 'notification.markAllAsRead',
    SEND_BULK: 'notification.sendBulk',
  },
  MEDIA: {
    FIND_ALL: 'media.findAll',
    FIND_BY_USER: 'media.findByUser',
    FIND_BY_ENTITY: 'media.findByEntity',
    FIND_ONE: 'media.findOne',
    CREATE: 'media.create',
    UPDATE: 'media.update',
    REMOVE: 'media.remove',
  },
  PROGRESS: {
    FIND_ALL: 'progress.findAll',
    FIND_BY_USER: 'progress.findByUser',
    FIND_BY_COURSE: 'progress.findByCourse',
    FIND_BY_USER_AND_COURSE: 'progress.findByUserAndCourse',
    FIND_ONE: 'progress.findOne',
    CREATE: 'progress.create',
    UPDATE: 'progress.update',
    DELETE: 'progress.delete',
    ADD_COMPLETED_LESSON: 'progress.addCompletedLesson',
    GENERATE_REPORT: 'progress.generateReport',
  },
};